eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: courtiers
          uri: http://localhost:8071
          predicates:
            - Path=/api/v1/courtiers/**
        - id: kitchens
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/tickets/**
        - id: orders
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/orders/**
        - id: restaurants
          uri: http://localhost:8072
          predicates:
            - Path=/api/v1/restaurants/**

management:
  tracing:
    sampling:
      probability: 1.0
